### PR TITLE
major update to reflect feedback from surveys and discussions

### PR DESCRIPTION
**Pull request by adamhajari**
@mindweather @dodeca @samirrayani @spucci @livbuli @alexwhite @julienbenatar @karlsluis @abigailricarte @jaytroop @britneeforeman @roycehaynes @tokenrain @kschrodes @bigbadace @cynthiameng @mpetrovich @prathinavelu

### CODE REVIEW

**Comment by dodeca** [comment]
:100:

**Comment by abigailricarte** [comment]
:+1:

**Comment by julienbenatar** [comment]
Great update

**Comment by bigbadace** [comment]
adam, great update!

-best
-ace


On Oct 9, 2015, at 12:20 PM, Adam Hajari <notifications@github.com<mailto:notifications@github.com>> wrote:


@mindweather<https://github.com/mindweather> @dodeca<https://github.com/dodeca> @samirrayani<https://github.com/samirrayani> @spucci<https://github.com/spucci> @livbuli<https://github.com/livbuli> @alexwhite<https://github.com/alexwhite> @julienbenatar<https://github.com/julienbenatar> @karlsluis<https://github.com/karlsluis> @abigailricarte<https://github.com/abigailricarte> @jaytroop<https://github.com/jaytroop> @britneeforeman<https://github.com/britneeforeman> @roycehaynes<https://github.com/roycehaynes> @toke nrain<https://github.com/tokenrain> @kschrodes<https://github.com/kschrodes> @bigbadace<https://github.com/bigbadace> @cynthiameng<https://github.com/cynthiameng> @mpetrovich<https://github.com/mpetrovich> @prathinavelu<https://github.com/prathinavelu>

________________________________
You can view, comment on, or merge this pull request online at:

  https://github.com/nextbigsoundinc/The-Way-We-Work/pull/21

Commit Summary

  *   major update to reflect feedback from feedback, survey, and discussions

File Changes

  *   M README.md<https://github.com/nextbigsoundinc/The-Way-We-Work/pull/21/files#diff-0> (66)

Patch Links:

  *   https://github.com/nextbigsoundinc/The-Way-We-Work/pull/21.patch
  *   https://github.com/nextbigsoundinc/The-Way-We-Work/pull/21.diff

**Pull request merged**
